
stages:
  - build
  - deploy

image: node:20
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

build:
  stage: build
  script:
    - npm ci
    - npm run build

test:
  stage: build
  script:
    - npm ci
    - npm run test
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov -t $CODECOV_TOKEN
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

publish-package:npmjs:
  stage: deploy
  script:
    - npm ci
    - npm config set //registry.npmjs.org/:_authToken ${NPMJS_TOKEN}
    - npm run semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
