
stages:
  - build
  - deploy

image: node:20
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

build:
  stage: build
  script:
    - npm ci
    - npm run build

test:
  stage: build
  script:
    - npm ci
    - npm run test
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

publish-package:
  stage: deploy
  script:
    - npm ci
    - rm .npmrc
    - echo "@nvax:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm run semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
